id = "mangabuddy"
version = "1.0.3"
backend = "wasm"
entrypoint = "mangabuddy.wasm"
plugin_api = "1"
capabilities = []
legacy_urls = ["mangabuddy.com", "www.mangabuddy.com", "mangak.io", "www.mangak.io"]
